In [2]:
import numpy as np

In [3]:
np.set_printoptions(precision=4)
x1= np.array([0.2, 3.1])
x2 = np.array([1.0, 3.0])
x3 = np.array([-0.2, 1.2])
x4 = np.array([1.0, 1.1])
y = np.array([1, 1, 0, 0])


X = np.array([x1, x2, x3, x4])
bias = np.array([0, 0, 0, 0])
X = np.column_stack((X, bias))
X

array([[ 0.2,  3.1,  0. ],
       [ 1. ,  3. ,  0. ],
       [-0.2,  1.2,  0. ],
       [ 1. ,  1.1,  0. ]])

In [4]:
w = np.array([-1, 0, 0]).T
w

array([-1,  0,  0])

In [5]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def next_weight(w, X, y):
    s = sigmoid(X.dot(w)) 
    grad = X.T.dot(s - y)
    
    s_prod = s.dot(1 - s)
    hessian = X.T.dot(s_prod).dot(X)

    hessian_inv = np.linalg.pinv(hessian)

    return w - hessian_inv.dot(grad)


In [6]:
s0 = sigmoid(X.dot(w))
s0

array([0.4502, 0.2689, 0.5498, 0.2689])

In [7]:
w1 = next_weight(w, X, y.T)
w1

array([-0.9385,  0.1428,  0.    ])

In [8]:
s1 = sigmoid(X.dot(w1))
s1

array([0.5634, 0.3752, 0.5888, 0.314 ])

In [9]:
w2 = next_weight(w1, X, y.T)
w2

array([-0.8846,  0.2406,  0.    ])